UPDATE "TRANSACTIONS" SET
		NAME = $NAME,
		TYPE_ID = $TYPE_ID,
		CLASS_ID = $CLASS_ID,
		PARENT_ENTITY_ID = $PARENT_ENTITY_ID,
		SOURCE_ACCOUNT_ID = $SOURCE_ACCOUNT_ID,
		AMOUNT = $AMOUNT,
		DATE = $DATE,
		TARGET_ACCOUNT_ID = $TARGET_ACCOUNT_ID,
		NOTES = $NOTES

		WHERE ID = $ID;
