CREATE TABLE "TYPES" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXT,
	"DESCRIPTION"	TEXT
);

CREATE TABLE "CLASSES" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXT,
	"PARENT_ID"	INTEGER,
	"FULL_NAME"	TEXT
);
